name: coffee_shop
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  dotted_dashed_line: ^0.0.3
  flutter_slidable: ^4.0.0
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.1
  cached_network_image: ^3.4.1
  firebase_auth: ^5.3.3
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - lib/assets/