// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsgGA8_fSwYf0SsNtRQqjJemw1xraBlWU',
    appId: '1:274596307222:web:47d30935d249b353f13037',
    messagingSenderId: '274596307222',
    projectId: 'coffee-shop-94b14',
    authDomain: 'coffee-shop-94b14.firebaseapp.com',
    databaseURL: 'https://coffee-shop-94b14-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coffee-shop-94b14.firebasestorage.app',
    measurementId: 'G-LKHES5HVPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0AIYctJgU4-6cO0wKkXQ13kOG320vPa8',
    appId: '1:274596307222:android:edde3061ecc25debf13037',
    messagingSenderId: '274596307222',
    projectId: 'coffee-shop-94b14',
    databaseURL: 'https://coffee-shop-94b14-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coffee-shop-94b14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3QZoI1jMQ5zPkC_y5GbdDoiS47bTjMpk',
    appId: '1:274596307222:ios:44864d4bde12b35af13037',
    messagingSenderId: '274596307222',
    projectId: 'coffee-shop-94b14',
    databaseURL: 'https://coffee-shop-94b14-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coffee-shop-94b14.firebasestorage.app',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3QZoI1jMQ5zPkC_y5GbdDoiS47bTjMpk',
    appId: '1:274596307222:ios:44864d4bde12b35af13037',
    messagingSenderId: '274596307222',
    projectId: 'coffee-shop-94b14',
    databaseURL: 'https://coffee-shop-94b14-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coffee-shop-94b14.firebasestorage.app',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsgGA8_fSwYf0SsNtRQqjJemw1xraBlWU',
    appId: '1:274596307222:web:7d2f79a6859581baf13037',
    messagingSenderId: '274596307222',
    projectId: 'coffee-shop-94b14',
    authDomain: 'coffee-shop-94b14.firebaseapp.com',
    databaseURL: 'https://coffee-shop-94b14-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coffee-shop-94b14.firebasestorage.app',
    measurementId: 'G-634PCH69CQ',
  );
}
